---
version: '3.8'

services:
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/links.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: darcula

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongo/


volumes:
  postgres-data:
