---
version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: darcula

volumes:
  db-data:
